In [1]:
import numpy as np

In [4]:
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [7]:
np.array([4.3, 3 ,4,5,])


array([4.3, 3. , 4. , 5. ])

In [9]:
Out[7]

array([4.3, 3. , 4. , 5. ])

In [10]:
type(Out[7])

numpy.ndarray

In [11]:
np.array([range(i,i+3) for i in (2,4,6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
l = [range(1,3)]

In [14]:
l

[range(1, 3)]

In [15]:
print(l)

[range(1, 3)]


In [16]:
l[1]

IndexError: list index out of range

In [17]:
np.array(range(1,3))

array([1, 2])

In [18]:
list(range(1,3))

[1, 2]

In [20]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.full((3,6),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.random.random((3,3))

array([[0.39726769, 0.46177644, 0.5230387 ],
       [0.81371508, 0.5019055 , 0.95117649],
       [0.70142039, 0.81676099, 0.4465772 ]])

In [29]:
np.random.normal(0,1,(3,3))

array([[ 0.36851486, -0.236344  , -0.16998109],
       [ 1.71031449,  0.77064373, -0.05612259],
       [ 1.17186913, -0.67642661,  1.41704051]])

In [30]:
np.random.randint(0,10,(3,3))

array([[6, 0, 2],
       [8, 4, 2],
       [2, 4, 0]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (3,4))
x3 = np.random.randint(10,size = (3,4,5))

x3.ndim, x3.shape, x3.size

(3, (3, 4, 5), 60)

In [33]:
x3.dtype

dtype('int32')

In [34]:
x3.itemsize

4

In [35]:
x3.nbytes

240

In [36]:
x1

array([5, 0, 3, 3, 7, 9])

In [43]:

np.random.randint(5,10,size = 6)

array([5, 5, 9, 7, 6, 5])

In [2]:
x1


array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [5]:
x2[2,3]

7

In [6]:
x1


array([5, 0, 3, 3, 7, 9])

In [12]:
x1[5:0:-1]

array([9, 7, 3, 3, 0])

In [3]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [6]:
x2[0,0] =12

In [7]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [8]:
print(x2[0,:])

[12  5  2  4]


In [9]:
print(x2[1])

[7 6 8 8]


In [10]:
x2_sub = x2[:2,:2]

In [11]:
x2_sub

array([[12,  5],
       [ 7,  6]])

In [12]:
x2_sub[0,1] = 13

In [13]:
x2

array([[12, 13,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [35]:
x = np.array([1,2,3])

In [33]:
x.ndim

1

In [37]:
x.shape

(3,)

In [38]:
x[0,1]

IndexError: too many indices for array

In [15]:
x

array([1, 2, 3])

In [16]:
x.reshape((1,3))

array([[1, 2, 3]])

In [17]:
print(x.reshape((1,3)))

[[1 2 3]]


In [18]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [22]:
x[2]

3

In [23]:
x.ndim

1

In [24]:
x.shape

(3,)

In [25]:
x2.shape

(3, 4)

In [26]:
x.size

3

In [27]:
type(x)

numpy.ndarray

In [28]:
x.ndim

1

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange?


In [4]:
ndarray?


Object `ndarray` not found.


In [8]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [9]:
x.reshape((1,3))

array([[1, 2, 3]])

In [11]:
x is x.reshape((1,3))

False

In [12]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [13]:
np.array?


In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


In [19]:
type(z)

numpy.ndarray